import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Link, Route, Routes, useLocation, useParams, useNavigate } from 'react-router-dom'
import { AnimatePresence, motion } from 'framer-motion'
import {
  ArrowRight, CalendarDays, Check, ChevronDown, Clock3, Compass, Globe2, Heart,
  LocateFixed, MapPin, Menu, MessageCircle, Navigation, Search, Send, Sparkles, Sun, X
} from 'lucide-react'
import './style.css'
import { getWeather, type WeatherResult } from './services/weatherService'
import { askTravelAssistant, generateItinerary } from './services/geminiService'
import { requestCurrentLocation } from './services/locationService'

const fallbackImage = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="1200" height="800" viewBox="0 0 1200 800"%3E%3Crect width="1200" height="800" fill="%23dfe9df"/%3E%3Cpath d="M0 620L300 360l180 150 180-220 540 430H0z" fill="%23a9c0a8"/%3E%3Ccircle cx="860" cy="210" r="90" fill="%23f4d59a"/%3E%3C/svg%3E'
function handleImageError(event: React.SyntheticEvent<HTMLImageElement>) {
  event.currentTarget.onerror = null
  event.currentTarget.src = fallbackImage
}

type Destination = {
  id: string; name: string; country: string; region: string; tagline: string; description: string
  image: string; coords: [number, number]; best: string; duration: string; currency: string; language: string; timezone: string
  places: { name: string; category: string; description: string; time: string; image: string }[]
}

const destinations: Destination[] = [
  { id:'paris', name:'Paris', country:'France', region:'Europe', tagline:'The City of Light', description:'A graceful tapestry of art, architecture, café culture and slow afternoons along the Seine.', image:'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1600&q=85', coords:[48.8566,2.3522], best:'Apr – Jun', duration:'4–5 days', currency:'Euro (€)', language:'French', timezone:'CET', places:[{name:'Eiffel Tower',category:'Landmark',description:'A defining symbol of Paris with panoramic views across the city.',time:'2–3 hours',image:'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=1000&q=80'},{name:'Louvre Museum',category:'Art & culture',description:'Lose an afternoon among masterpieces in the world’s largest museum.',time:'3–4 hours',image:'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=1000&q=80'},{name:'Montmartre',category:'Neighbourhood',description:'Wander cobbled lanes, artists’ studios and the steps of Sacré-Cœur.',time:'2–3 hours',image:'https://images.unsplash.com/photo-1503917988258-f87a78e3c995?auto=format&fit=crop&w=1000&q=80'}]},
  { id:'tokyo', name:'Tokyo', country:'Japan', region:'Asia', tagline:'Where tradition meets tomorrow', description:'A kinetic city of quiet shrines, neon nights, exceptional food and impeccable design.', image:'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1600&q=85', coords:[35.6762,139.6503], best:'Mar – May', duration:'5–7 days', currency:'Yen (¥)', language:'Japanese', timezone:'JST', places:[{name:'Senso-ji Temple',category:'Heritage',description:'Begin in Asakusa at Tokyo’s oldest temple and its lantern-lined approach.',time:'1–2 hours',image:'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=1000&q=80'},{name:'Shibuya Crossing',category:'City icon',description:'Feel the pulse of the city at its most cinematic intersection.',time:'1 hour',image:'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1000&q=80'}]},
  { id:'bali', name:'Bali', country:'Indonesia', region:'Asia', tagline:'Find your slower side', description:'Emerald rice terraces, volcanic beaches and a culture built around beauty and balance.', image:'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1600&q=85', coords:[-8.4095,115.1889], best:'May – Oct', duration:'6–8 days', currency:'Rupiah (Rp)', language:'Indonesian', timezone:'WITA', places:[{name:'Tegallalang Rice Terraces',category:'Nature',description:'Watch the morning light spill over Bali’s sculpted emerald hillsides.',time:'2 hours',image:'https://images.unsplash.com/photo-1539367628448-4bc5c9d171c8?auto=format&fit=crop&w=1000&q=80'},{name:'Uluwatu Temple',category:'Heritage',description:'A clifftop temple with ocean sunsets and a famous Kecak dance.',time:'3 hours',image:'https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=1000&q=80'}]},
  { id:'dubai', name:'Dubai', country:'United Arab Emirates', region:'Asia', tagline:'A city of ambitious contrasts', description:'Desert horizons, contemporary architecture and warm Gulf hospitality in one bold skyline.', image:'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1600&q=85', coords:[25.2048,55.2708], best:'Nov – Mar', duration:'3–4 days', currency:'Dirham (د.إ)', language:'Arabic', timezone:'GST', places:[{name:'Burj Khalifa',category:'Architecture',description:'Rise above the city for one of the world’s great urban views.',time:'2 hours',image:'https://images.unsplash.com/photo-1526495124232-a04e1849168c?auto=format&fit=crop&w=1000&q=80'},{name:'Al Fahidi Historic District',category:'Culture',description:'Discover wind towers, galleries and old Dubai beside the creek.',time:'2–3 hours',image:'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1000&q=80'}]},
  { id:'london', name:'London', country:'United Kingdom', region:'Europe', tagline:'History in every neighbourhood', description:'Grand museums, leafy parks and a creative pulse that makes every visit feel new.', image:'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1600&q=85', coords:[51.5072,-.1276], best:'May – Sep', duration:'4–6 days', currency:'Pound (£)', language:'English', timezone:'GMT', places:[{name:'Tower Bridge',category:'Landmark',description:'Walk the glass floor and riverfront paths around London’s most iconic bridge.',time:'1–2 hours',image:'https://images.unsplash.com/photo-1529655683826-aba9b3e77383?auto=format&fit=crop&w=1000&q=80'},{name:'Borough Market',category:'Food',description:'Taste your way through one of the city’s most beloved food halls.',time:'2 hours',image:'https://images.unsplash.com/photo-1488747279002-c8523379faaa?auto=format&fit=crop&w=1000&q=80'}]},
  { id:'rome', name:'Rome', country:'Italy', region:'Europe', tagline:'The eternal city', description:'Ancient ruins, late dinners and a living museum where every corner rewards wandering.', image:'https://images.unsplash.com/photo-1529260830199-42c24126f198?auto=format&fit=crop&w=1600&q=85', coords:[41.9028,12.4964], best:'Apr – Jun', duration:'3–5 days', currency:'Euro (€)', language:'Italian', timezone:'CET', places:[{name:'Colosseum',category:'Ancient history',description:'Step into the amphitheatre that has defined Rome for nearly two millennia.',time:'2 hours',image:'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1000&q=80'},{name:'Trastevere',category:'Neighbourhood',description:'Spend an evening among ivy-covered lanes and trattorias.',time:'3 hours',image:'https://images.unsplash.com/photo-1541370976299-4d24ebbc9077?auto=format&fit=crop&w=1000&q=80'}]},
  { id:'new-york', name:'New York', country:'United States', region:'North America', tagline:'The city that never stands still', description:'A world of neighbourhoods, galleries, rooftops and energy that is impossible to imitate.', image:'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?auto=format&fit=crop&w=1600&q=85', coords:[40.7128,-74.006], best:'Sep – Nov', duration:'4–6 days', currency:'Dollar ($)', language:'English', timezone:'EST', places:[{name:'Central Park',category:'Outdoors',description:'Trade the vertical city for 843 acres of paths, lakes and quiet corners.',time:'2–4 hours',image:'https://images.unsplash.com/photo-1518391846015-55a9cc003b25?auto=format&fit=crop&w=1000&q=80'},{name:'The High Line',category:'Design',description:'Walk a planted rail line above the West Side for a fresh city perspective.',time:'1–2 hours',image:'https://images.unsplash.com/photo-1522083165195-3424ed129620?auto=format&fit=crop&w=1000&q=80'}]},
  { id:'singapore', name:'Singapore', country:'Singapore', region:'Asia', tagline:'Nature, future, flavour', description:'A tropical city-state where hawker stalls, lush gardens and bold architecture coexist.', image:'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1600&q=85', coords:[1.3521,103.8198], best:'Feb – Apr', duration:'3–4 days', currency:'Dollar (S$)', language:'English', timezone:'SGT', places:[{name:'Gardens by the Bay',category:'Nature & design',description:'Explore Supertrees and conservatories in Singapore’s futuristic garden.',time:'3 hours',image:'https://images.unsplash.com/photo-1508964942454-1a56651d54ac?auto=format&fit=crop&w=1000&q=80'},{name:'Maxwell Food Centre',category:'Food',description:'A delicious introduction to the city’s layered hawker culture.',time:'1–2 hours',image:'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1000&q=80'}]},
  { id:'sydney', name:'Sydney', country:'Australia', region:'Oceania', tagline:'The good life, by the water', description:'Sunlit beaches, harbour icons and a relaxed food scene at the edge of the Pacific.', image:'https://images.unsplash.com/photo-1524820197278-540916411e20?auto=format&fit=crop&w=1600&q=85', coords:[-33.8688,151.2093], best:'Sep – Nov', duration:'4–6 days', currency:'Dollar (A$)', language:'English', timezone:'AEST', places:[{name:'Sydney Opera House',category:'Architecture',description:'See the harbour’s defining sails from the water or the Royal Botanic Garden.',time:'2 hours',image:'https://images.unsplash.com/photo-1624138784614-87fd1b6528f8?auto=format&fit=crop&w=1000&q=80'},{name:'Bondi to Coogee Walk',category:'Outdoors',description:'A spectacular coastal trail linking some of Sydney’s best beaches.',time:'2–3 hours',image:'https://images.unsplash.com/photo-1524293581917-878a6d017c71?auto=format&fit=crop&w=1000&q=80'}]},
  { id:'cape-town', name:'Cape Town', country:'South Africa', region:'Africa', tagline:'Where mountain meets ocean', description:'A dramatic peninsula of vineyards, beaches, design and wild landscapes.', image:'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=1600&q=85', coords:[-33.9249,18.4241], best:'Nov – Mar', duration:'4–6 days', currency:'Rand (R)', language:'English', timezone:'SAST', places:[{name:'Table Mountain',category:'Nature',description:'Take in the peninsula’s cinematic geography from the summit.',time:'3–5 hours',image:'https://images.unsplash.com/photo-1576485290814-1c72aa4bbb8e?auto=format&fit=crop&w=1000&q=80'},{name:'Bo-Kaap',category:'Culture',description:'A colourful neighbourhood with deep Cape Malay history and flavour.',time:'2 hours',image:'https://images.unsplash.com/photo-1576485290814-1c72aa4bbb8e?auto=format&fit=crop&w=1000&q=80'}]}
]

function App() {
  const [saved, setSaved] = useState<string[]>([])
  const [chatOpen, setChatOpen] = useState(false)
  const [plannerOpen, setPlannerOpen] = useState(false)
  const [locationOpen, setLocationOpen] = useState(false)
  const [location, setLocation] = useState<string | null>(null)
  const [locationWeather, setLocationWeather] = useState<{ temp: number; condition: string } | null>(null)
  const route = useLocation()
  const navigate = useNavigate()
  const context = destinations.find(d => route.pathname.includes(`/destinations/${d.id}`))
  const handleUseLocation = async () => {
    try {
      const position = await requestCurrentLocation()
      const currentWeather = await getWeather([position.coords.latitude, position.coords.longitude])
      setLocation(`${position.coords.latitude.toFixed(2)}, ${position.coords.longitude.toFixed(2)}`)
      setLocationWeather({ temp: currentWeather.temp, condition: currentWeather.condition })
      setLocationOpen(false)
    } catch (error) {
      setLocationWeather(null)
      setLocationOpen(true)
    }
  }
  return <div className="app">
    <Navbar onPlan={()=>setPlannerOpen(true)} onLocation={()=>setLocationOpen(true)} />
    <Routes>
      <Route path="/" element={<Home onPlan={()=>setPlannerOpen(true)} onLocation={handleUseLocation} saved={saved} toggleSave={id=>setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])} />} />
      <Route path="/destinations" element={<Destinations saved={saved} toggleSave={id=>setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])} />} />
      <Route path="/destinations/:id" element={<Details saved={saved} toggleSave={id=>setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])} onPlan={()=>setPlannerOpen(true)} />} />
      <Route path="/itinerary" element={<Itinerary />} />
      <Route path="*" element={<NotFound />} />
    </Routes>
    <Footer />
    <button className="ai-fab" onClick={()=>setChatOpen(true)} aria-label="Ask Wanderly AI"><Sparkles size={18}/> Ask Wanderly AI</button>
    <AnimatePresence>{chatOpen && <Chat onClose={()=>setChatOpen(false)} context={context} />}{plannerOpen && <Planner onClose={()=>setPlannerOpen(false)} />}{locationOpen && <LocationModal onClose={()=>setLocationOpen(false)} onUse={handleUseLocation} onManual={city=>{setLocation(city);setLocationOpen(false);const destination=destinations.find(d=>`${d.name}, ${d.country}`===city);if(destination) navigate(`/destinations/${destination.id}`)}} />}</AnimatePresence>
    {location && <div className="toast"><LocateFixed size={16}/> Location ready: {location}{locationWeather&&<span> · {locationWeather.temp}°C, {locationWeather.condition}</span>}<button onClick={()=>{setLocation(null);setLocationWeather(null)}}><X size={15}/></button></div>}
  </div>
}

function Navbar({onPlan,onLocation}:{onPlan:()=>void;onLocation:()=>void}) {
  const [open,setOpen]=useState(false)
  const [scrolled,setScrolled]=useState(false)
  useEffect(()=>{const handleScroll=()=>setScrolled(window.scrollY>24);handleScroll();window.addEventListener('scroll',handleScroll,{passive:true});return()=>window.removeEventListener('scroll',handleScroll)},[])
  return <header className={scrolled?'navbar scrolled':'navbar'}><Link to="/" className="brand"><span className="brand-mark"><Compass size={18}/></span>Wanderly</Link><nav className={open?'nav-links open':'nav-links'}><Link to="/destinations" onClick={()=>setOpen(false)}>Explore</Link><Link to="/destinations" onClick={()=>setOpen(false)}>Destinations</Link><Link to="/itinerary" onClick={()=>setOpen(false)}>AI Planner</Link></nav><div className="nav-actions"><button className="location-btn" onClick={onLocation}><LocateFixed size={16}/> <span>My location</span></button><button className="button button-dark compact" onClick={onPlan}>Start planning <ArrowRight size={15}/></button></div><button className="menu-btn" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button></header>
}

function Home({onPlan,onLocation,saved,toggleSave}:{onPlan:()=>void;onLocation:()=>void;saved:string[];toggleSave:(id:string)=>void}) {
  const navigate = useNavigate()
  return <main><section className="hero"><video autoPlay muted loop playsInline poster={destinations[0].image} onError={e=>{e.currentTarget.style.display='none'}}><source src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" type="video/mp4"/></video><div className="hero-overlay"/><div className="hero-content"><motion.p initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="eyebrow">Wander with purpose</motion.p><motion.h1 initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.1}}>Go somewhere<br/><em>you'll remember.</em></motion.h1><motion.p className="hero-copy" initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:.2}}>Discover remarkable places, understand the moment, and let Wanderly shape the journey.</motion.p><div className="hero-search"><Search size={19}/><input aria-label="Search destinations" placeholder="Search destinations..." onKeyDown={e=>{if(e.key==='Enter') navigate('/destinations')}}/><button onClick={()=>navigate('/destinations')}>Search</button></div><div className="hero-links"><button onClick={()=>navigate('/destinations')}>Explore destinations <ArrowRight size={16}/></button><button onClick={onPlan}><Sparkles size={16}/> Plan my trip</button></div><button className="use-location" onClick={onLocation}><LocateFixed size={15}/> Use my current location</button></div><div className="scroll-indicator"><span/> Scroll to explore</div></section><section className="section featured"><div className="section-heading"><div><p className="eyebrow accent">Curated for you</p><h2>Places worth <em>going</em></h2></div><Link to="/destinations" className="text-link">View all destinations <ArrowRight size={16}/></Link></div><p className="section-intro">Explore destinations chosen for unforgettable experiences.</p><div className="destination-grid">{destinations.slice(0,6).map((d,i)=><DestinationCard key={d.id} d={d} index={i} saved={saved.includes(d.id)} toggleSave={toggleSave}/>)}</div></section><section className="manifesto"><div className="manifesto-art"><img loading="lazy" src={destinations[2].image} alt="Bali rice terraces"/></div><div className="manifesto-copy"><p className="eyebrow accent">The Wanderly way</p><h2>Go beyond<br/><em>the postcard.</em></h2><p>We believe the best trips have room for the unexpected. Wanderly brings the context, the inspiration and the tools — you bring the curiosity.</p><button className="button button-dark" onClick={onPlan}>Build your trip <ArrowRight size={16}/></button></div></section></main>
}

function DestinationCard({d,index,saved,toggleSave}:{d:Destination;index:number;saved:boolean;toggleSave:(id:string)=>void}) {
  const [weather,setWeather]=useState<WeatherResult|null>(null)
  const [weatherError,setWeatherError]=useState(false)
  useEffect(()=>{let active=true;getWeather(d.coords).then(result=>{if(active)setWeather(result)}).catch(()=>{if(active)setWeatherError(true)});return()=>{active=false}},[d.coords])
  return <motion.article className="destination-card" initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.05}}><Link to={`/destinations/${d.id}`}><div className="card-image"><img loading="lazy" src={d.image} onError={handleImageError} alt={`${d.name}, ${d.country}`}/><span className="region-tag">{d.region}</span><button className={saved?'save active':'save'} onClick={e=>{e.preventDefault();toggleSave(d.id)}} aria-label="Save destination"><Heart size={17} fill={saved?'currentColor':'none'}/></button></div><div className="card-body"><div className="card-title"><div><h3>{d.name}</h3><p>{d.country}</p></div><ArrowRight className="card-arrow" size={19}/></div><p className="card-desc">{d.description}</p><div className="weather-preview"><Sun size={16}/>{weather?<><strong>{weather.temp}°C</strong><span>{weather.condition}</span></>:<span>{weatherError?'Weather unavailable':'Loading weather…'}</span>}</div></div></Link></motion.article>
}

function Destinations({saved,toggleSave}:{saved:string[];toggleSave:(id:string)=>void}) {
  const [query,setQuery]=useState(''); const [region,setRegion]=useState('All'); const [sort,setSort]=useState('Popular')
  const filtered=useMemo(()=>destinations.filter(d=>(region==='All'||d.region===region)&&`${d.name} ${d.country} ${d.region} ${d.tagline} ${d.description} ${d.places.map(place=>place.name).join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='Name'?a.name.localeCompare(b.name):0),[query,region,sort])
  return <main className="page"><div className="page-hero"><p className="eyebrow accent">Open the atlas</p><h1>Explore the <em>world.</em></h1><p>Find your next destination, from city lights to wild horizons.</p></div><section className="explorer section"><div className="filter-bar"><div className="search-input"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search destinations"/></div><div className="select-wrap"><select value={sort} onChange={e=>setSort(e.target.value)}><option>Popular</option><option>Name</option></select><ChevronDown size={15}/></div></div><div className="chips">{['All','Asia','Europe','North America','South America','Africa','Oceania'].map(r=><button className={region===r?'chip active':'chip'} onClick={()=>setRegion(r)} key={r}>{r}</button>)}</div>{filtered.length?<div className="destination-grid explorer-grid">{filtered.map((d,i)=><DestinationCard key={d.id} d={d} index={i} saved={saved.includes(d.id)} toggleSave={toggleSave}/>)}</div>:<div className="empty"><Globe2 size={30}/><h3>No destinations found</h3><p>Try another search or region.</p></div>}</section></main>
}

function Details({saved,toggleSave,onPlan}:{saved:string[];toggleSave:(id:string)=>void;onPlan:()=>void}) {
  const {id}=useParams(); const d=destinations.find(x=>x.id===id); const [weather,setWeather]=useState<any>(null); const [loading,setLoading]=useState(true)
  useEffect(()=>{if(d){setLoading(true);getWeather(d.coords).then(setWeather).catch(error=>setWeather({error:true,message:error instanceof Error?error.message:'Weather is temporarily unavailable.'})).finally(()=>setLoading(false))}},[d])
  if(!d) return <NotFound/>
  return <main className="details"><section className="detail-hero"><img src={d.image} onError={handleImageError} alt={`${d.name}, ${d.country}`}/><div className="detail-overlay"/><div className="detail-top"><Link to="/destinations" className="back-link">← Back to destinations</Link><div><button className="icon-btn" onClick={()=>toggleSave(d.id)} aria-label="Save destination"><Heart size={18} fill={saved.includes(d.id)?'currentColor':'none'}/></button><button className="icon-btn" aria-label="Share destination">↗</button></div></div><div className="detail-heading"><p className="eyebrow">Destination guide</p><h1>{d.name}</h1><p>{d.country} <span>·</span> {d.tagline}</p></div></section><section className="detail-content"><div className="overview"><p className="eyebrow accent">A little context</p><h2>Make it <em>meaningful.</em></h2><p className="lead">{d.description}</p><div className="facts"><Fact icon={<CalendarDays/>} label="Best time" value={d.best}/><Fact icon={<Clock3/>} label="Suggested stay" value={d.duration}/><Fact icon={<Globe2/>} label="Currency" value={d.currency}/><Fact icon={<MessageCircle/>} label="Language" value={d.language}/><Fact icon={<Navigation/>} label="Time zone" value={d.timezone}/></div></div><Weather weather={weather} loading={loading} name={d.name}/></section><section className="places section"><div className="section-heading"><div><p className="eyebrow accent">The essentials</p><h2>Don't <em>miss these.</em></h2></div><button className="button button-dark" onClick={onPlan}><Sparkles size={16}/> Plan my trip</button></div><div className="places-grid">{d.places.map((p,i)=><motion.article className="place-card" key={p.name} initial={{opacity:0,y:15}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.08}}><img src={p.image} onError={handleImageError} alt={p.name}/><div className="place-body"><span className="place-category">{p.category}</span><h3>{p.name}</h3><p>{p.description}</p><div className="place-meta"><Clock3 size={14}/> Recommended time: {p.time}</div></div></motion.article>)}</div></section></main>
}

function Fact({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="fact"><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div>}
function Weather({weather,loading,name}:{weather:any;loading:boolean;name:string}) { return <div className="weather-card"><div className="weather-top"><div><p className="eyebrow accent">Live conditions</p><h3>{name} weather</h3></div><span className="updated">Updated just now</span></div>{loading?<div className="weather-loading"><span/><span/><span/></div>:weather?.error?<div className="weather-error">{weather.message || 'Weather is temporarily unavailable.'}</div>:<><div className="current-weather"><img src={`https://openweathermap.org/img/wn/${weather.icon}@2x.png`} onError={handleImageError} alt={weather.condition}/><div><strong>{weather.temp}°</strong><span>{weather.condition}</span></div></div><div className="weather-details"><div><small>Feels like</small><strong>{weather.feels}°</strong></div><div><small>Humidity</small><strong>{weather.humidity}%</strong></div><div><small>Wind</small><strong>{weather.wind} km/h</strong></div><div><small>Visibility</small><strong>{weather.visibility} km</strong></div><div><small>Pressure</small><strong>{weather.pressure} hPa</strong></div></div></>}</div> }

function Planner({onClose}:{onClose:()=>void}) { const [done,setDone]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [destination,setDestination]=useState('Paris'); const [days,setDays]=useState(4); const [style,setStyle]=useState('Balanced'); const [interests,setInterests]=useState(''); const navigate=useNavigate(); const generate=async()=>{setBusy(true);setError('');try{const result=await generateItinerary({destination,days,style,interests});sessionStorage.setItem('wanderly-itinerary',JSON.stringify(result));setDone(true)}catch(e){setError(e instanceof Error?e.message:'Could not generate itinerary')}finally{setBusy(false)}}; return <motion.div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Plan your trip" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div className="planner-modal" initial={{y:30,opacity:0}} animate={{y:0,opacity:1}} exit={{y:30,opacity:0}}><button className="modal-close" onClick={onClose} aria-label="Close planner"><X/></button>{done?<div className="planner-done"><Check size={28}/><p className="eyebrow accent">Your trip is taking shape</p><h2>Your {destination} itinerary<br/><em>is ready.</em></h2><p>We’ve mapped out a thoughtful {days}-day journey with room to wander.</p><button className="button button-dark" onClick={()=>{onClose();navigate('/itinerary')}}>View itinerary <ArrowRight size={16}/></button></div>:<><p className="eyebrow accent">Your trip, your way</p><h2>Plan something <em>great.</em></h2><p className="modal-intro">Tell us what you’re in the mood for and let Wanderly do the rest.</p><label>Destination<div className="form-select"><select value={destination} onChange={e=>setDestination(e.target.value)}>{destinations.map(d=><option key={d.id}>{d.name}</option>)}</select><ChevronDown size={16}/></div></label><div className="form-row"><label>How many days<div className="form-select"><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={3}>3 days</option><option value={4}>4 days</option><option value={5}>5 days</option><option value={7}>7 days</option></select><ChevronDown size={16}/></div></label><label>Travel style<div className="form-select"><select value={style} onChange={e=>setStyle(e.target.value)}><option>Balanced</option><option>Relaxed</option><option>Adventure</option><option>Culture</option><option>Food</option><option>Luxury</option><option>Budget</option></select><ChevronDown size={16}/></div></label></div><label>Interests <span className="optional">Optional</span><input className="form-control" value={interests} onChange={e=>setInterests(e.target.value)} placeholder="History, food, photography..."/></label>{error&&<p className="form-error">{error}</p>}<button className="button button-dark full" onClick={generate} disabled={busy}>{busy?'Generating your route...':'Generate itinerary'} <Sparkles size={16}/></button></>}</motion.div></motion.div> }

function Chat({onClose,context}:{onClose:()=>void;context?:Destination}) { const [messages,setMessages]=useState<{role:'user'|'ai';text:string}[]>([{role:'ai',text:context?`Hi, I’m Wanderly AI. Ask me anything about ${context.name}.`:'Hi, I’m Wanderly AI. Where are you dreaming of going?'}]); const [input,setInput]=useState(''); const [lastQuestion,setLastQuestion]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const send=async(questionOverride?:string)=>{const question=(questionOverride??input).trim();if(!question||busy)return;setInput('');setLastQuestion(question);setError('');setMessages(m=>[...m,{role:'user',text:question}]);setBusy(true);try{const answer=await askTravelAssistant(question,context&&{name:context.name,country:context.country,places:context.places.map(p=>p.name)});setMessages(m=>[...m,{role:'ai',text:answer}])}catch(e){setError(e instanceof Error?e.message:'Assistant is unavailable');setMessages(m=>[...m,{role:'ai',text:'I’m having trouble connecting right now. You can still explore the guide below, or try again in a moment.'}])}finally{setBusy(false)}}; return <motion.div className="chat-drawer" role="dialog" aria-modal="true" aria-label="Wanderly AI" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}}><div className="chat-head"><div><span className="ai-icon"><Sparkles size={16}/></span><div><strong>Wanderly AI</strong><small>{context?`Exploring ${context.name}`:'Your personal travel assistant'}</small></div></div><div className="chat-head-actions"><button onClick={()=>setMessages([{role:'ai',text:'Conversation cleared. Where should we wander next?'}])} aria-label="Clear conversation">Clear</button><button onClick={onClose} aria-label="Close assistant"><X/></button></div></div><div className="chat-messages">{messages.map((m,i)=><div className={m.role==='user'?'message user':'message'} key={i}>{m.text}</div>)}{busy&&<div className="typing"><span/><span/><span/></div>}{error&&lastQuestion&&<button className="retry" onClick={()=>send(lastQuestion)}>Retry</button>}<div className="suggestions">{['How many days should I spend here?','What should I see?','When should I visit?','What should I eat?','Is this destination expensive?','Plan my trip'].map(q=><button key={q} onClick={()=>send(q)}>{q}</button>)}</div></div><div className="chat-input"><input aria-label="Message Wanderly AI" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask anything about travel..."/><button onClick={()=>send()} aria-label="Send message"><Send size={17}/></button></div></motion.div> }

function LocationModal({onClose,onUse,onManual}:{onClose:()=>void;onUse:()=>void;onManual:(city:string)=>void}) { const [query,setQuery]=useState(''); const matches=destinations.filter(d=>`${d.name} ${d.country}`.toLowerCase().includes(query.toLowerCase())).slice(0,5); return <motion.div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Choose your location" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div className="planner-modal location-modal" initial={{y:30,opacity:0}} animate={{y:0,opacity:1}} exit={{y:30,opacity:0}}><button className="modal-close" onClick={onClose} aria-label="Close location dialog"><X/></button><p className="eyebrow accent">Make it personal</p><h2>Discover places<br/><em>around you.</em></h2><p className="modal-intro">Allow Wanderly to use your location for a more relevant travel experience, or choose a city manually.</p><button className="button button-dark full" onClick={onUse}><LocateFixed size={16}/> Use my location</button><div className="or-divider">or search manually</div><div className="search-input manual-search"><Search size={17}/><input autoFocus aria-label="Search for a city" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search for a city"/></div>{query&&<div className="location-results">{matches.map(d=><button key={d.id} onClick={()=>onManual(`${d.name}, ${d.country}`)}><MapPin size={14}/><span>{d.name}<small>{d.country}</small></span></button>)}{!matches.length&&<p>No matching city in the guide.</p>}</div>}</motion.div></motion.div> }

function Itinerary(){ const fallback={destination:'Paris',country:'France',duration:4,summary:'A balanced four-day Paris itinerary.',days:[{day:1,title:'Iconic Paris',activities:[['09:00','Breakfast at a corner café','Saint-Germain-des-Prés'],['10:30','Eiffel Tower','Champ de Mars'],['13:00','Lunch along the Seine','7th arrondissement'],['15:00','Louvre Museum','Rue de Rivoli']]},{day:2,title:'Art & atmosphere',activities:[['09:30','Coffee and croissants','Montmartre'],['11:00','Sacré-Cœur','Montmartre'],['13:30','Market lunch','Rue des Abbesses'],['15:30','Musée d’Orsay','Quai Anatole France']]},{day:3,title:'The Parisian table',activities:[['10:00','Marché Bastille','Place de la Bastille'],['12:30','Cooking class','Le Marais'],['16:00','Place des Vosges','Le Marais'],['20:00','Dinner reservation','Canal Saint-Martin']]},{day:4,title:'A final slow morning',activities:[['09:00','Breakfast by the canal','Canal Saint-Martin'],['11:00','Seine river walk','Pont Neuf'],['13:00','Farewell lunch','Saint-Germain-des-Prés']]}]}; const [data]=useState<any>(()=>{try{return JSON.parse(sessionStorage.getItem('wanderly-itinerary')||'null')||fallback}catch{return fallback}}); return <main className="page itinerary-page"><div className="page-hero"><p className="eyebrow accent">Made for wandering</p><h1>Your {data.destination} <em>itinerary.</em></h1><p>{data.duration} days · {data.destination}, {data.country} · Thoughtfully paced</p></div><section className="timeline section">{data.days.map((day:any)=><div className="day" key={day.day}><div className="day-label">DAY {String(day.day).padStart(2,'0')}</div><div className="day-content"><h2>{day.title}</h2>{day.activities.map((a:any)=>{const activity=Array.isArray(a)?{time:a[0],title:a[1],location:a[2]}:a;return <div className="activity" key={`${day.day}-${activity.time}-${activity.title}`}><time>{activity.time}</time><div><h3>{activity.title}</h3><p><MapPin size={13}/>{activity.location}</p>{activity.description&&<span className="activity-description">{activity.description}</span>}</div><ArrowRight size={16}/></div>})}</div></div>)}</section></main>}
function NotFound(){return <main className="not-found"><Compass size={40}/><h1>Not all who wander are lost.</h1><p>This page is somewhere else.</p><Link to="/destinations" className="button button-dark">Explore destinations</Link></main>}
function Footer(){return <footer><div><Link to="/" className="brand"><span className="brand-mark"><Compass size={18}/></span>Wanderly</Link><p>Explore more. Travel better.</p></div><div className="footer-links"><Link to="/destinations">Explore</Link><Link to="/destinations">Destinations</Link><Link to="/itinerary">AI Planner</Link><a href="#">About</a></div><small>Built as a front-end travel experience.</small></footer>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><App/></BrowserRouter></React.StrictMode>)
